### ISSUE TITLE
Upgrade: mute

### ISSUE THREAD

**Issue by Asgoret** [Asgoret/devopshelper_bot#12]
Add diversity of time:

- [ ] hours
- [ ] weeks
- [ ] years

**Comment by botayhard** [comment]
In api docs indicated:
`If user is restricted for more than 366 days or less than 30 seconds from the current time, they are considered to be restricted forever`

Maybe better options for

- [ ] hours

- [ ] days

- [ ] weeks

- [ ] indefinitely
